# Generated by Django 4.0.6 on 2023-04-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_total_votes_project_votes_ratio_review_and_more'),
        ('projects', '0004_alter_project_image'),
    ]

    operations = [
    ]
