# Generated by Django 4.0.6 on 2023-04-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_merge_20230421_1421'),
        ('projects', '0007_alter_tag_slug'),
    ]

    operations = [
    ]
